### ISSUE TITLE
How is it better than/different from pip-tools?

### ISSUE THREAD

**Issue by bfo** [mrzechonek/python-pippin#1]
https://github.com/jazzband/pip-tools

**Comment by mrzechonek** [comment]
It integrates with setup.py, so you don't need separate files: setup.py for packaging, then req-test.in for tests and req-dev.in for development.

By the way, extracting test dependencies from setup breaks `./setup.py test`, and there doesn't seem to be a way around it.

**Comment by mrzechonek** [comment]
Otoh, it might he better to submit this as a PR to pip tools.

**Comment by bfo** [comment]
Having skimmed pip-tools repo I got an impression they do `setup.py` as well.

https://github.com/jazzband/pip-tools#requirements-from-setuppy

```
Requirements from setup.py

Suppose you have a Django project, and want to pin it for production. If you have a setup.py with install_requires=['django'], then run pip-compile without any arguments
```

**Comment by mrzechonek** [comment]
Yes, but only for install_requires. For tests/develop you need to keep .in files.
